name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Unet
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} 
          key: ${{secrets.SSH_KEY}}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
     
          script: |
            mkdir Tverdun
            cd Tverdun
            git clone https://github.com/YaroslavTverdun/Gigantonio.git
            echo 'Deployment successful to DigitalOcean'
